// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using slowfit.DBModels;

#nullable disable

namespace slowfit.Migrations
{
    [DbContext(typeof(SlowFitContext))]
    [Migration("20250626103516_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("slowfit.DBModels.Answer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("answerId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnswerId"));

                    b.Property<string>("AnswerString")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("answerString");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int")
                        .HasColumnName("questionId");

                    b.HasKey("AnswerId");

                    b.HasIndex("QuestionId");

                    b.ToTable("answer", (string)null);
                });

            modelBuilder.Entity("slowfit.DBModels.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("appointmentId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<string>("CallUrl")
                        .HasMaxLength(350)
                        .IsUnicode(false)
                        .HasColumnType("varchar(350)")
                        .HasColumnName("callUrl");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("description");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<int>("PtId")
                        .HasColumnType("int")
                        .HasColumnName("ptId");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("AppointmentId");

                    b.HasIndex("UserId");

                    b.ToTable("appointment", (string)null);
                });

            modelBuilder.Entity("slowfit.DBModels.Billing", b =>
                {
                    b.Property<int>("BillingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("billingId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillingId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("amount");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("date");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("orderId");

                    b.Property<int>("PaymentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("paymentTypeId");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("BillingId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PaymentTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("billing", (string)null);
                });

            modelBuilder.Entity("slowfit.DBModels.BodyPart", b =>
                {
                    b.Property<int>("BodyPartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("bodyPartId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BodyPartId"));

                    b.Property<string>("BodyPartName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("bodyPartName");

                    b.HasKey("BodyPartId");

                    b.ToTable("bodyPart", (string)null);
                });

            modelBuilder.Entity("slowfit.DBModels.CategoryOfDay", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("categoryId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("MomentOfDay")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("momentOfDay");

                    b.HasKey("CategoryId");

                    b.ToTable("categoryOfDay", (string)null);
                });

            modelBuilder.Entity("slowfit.DBModels.DetailExercise", b =>
                {
                    b.Property<int>("DetailExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("detailExerciseId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailExerciseId"));

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int")
                        .HasColumnName("exerciseId");

                    b.Property<int?>("NRipetition")
                        .HasColumnType("int")
                        .HasColumnName("nRipetition");

                    b.Property<int?>("Pause")
                        .HasColumnType("int")
                        .HasColumnName("pause");

                    b.Property<string>("Phase")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phase");

                    b.Property<int?>("Series")
                        .HasColumnType("int")
                        .HasColumnName("series");

                    b.Property<int>("TrainingId")
                        .HasColumnType("int")
                        .HasColumnName("trainingId");

                    b.HasKey("DetailExerciseId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TrainingId");

                    b.ToTable("detailExercise", (string)null);
                });

            modelBuilder.Entity("slowfit.DBModels.Exercise", b =>
                {
                    b.Property<int>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("exerciseId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExerciseId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Image")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("image");

                    b.Property<int>("LocationTrainingId")
                        .HasColumnType("int")
                        .HasColumnName("locationTrainingId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("TypeTrainingId")
                        .HasColumnType("int")
                        .HasColumnName("typeTrainingId");

                    b.Property<string>("UrlVideo")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("urlVideo");

                    b.HasKey("ExerciseId");

                    b.HasIndex("LocationTrainingId");

                    b.ToTable("exercise", (string)null);
                });

            modelBuilder.Entity("slowfit.DBModels.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ingredientId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientId"));

                    b.Property<int?>("Calories")
                        .HasColumnType("int")
                        .HasColumnName("calories");

                    b.Property<decimal?>("Carbohydrate")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("carbohydrate");

                    b.Property<decimal?>("Fats")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("fats");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<decimal?>("Protein")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("protein");

                    b.HasKey("IngredientId");

                    b.ToTable("ingredient", (string)null);
                });

            modelBuilder.Entity("slowfit.DBModels.InputType", b =>
                {
                    b.Property<int>("InputTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("inputTypeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InputTypeId"));

                    b.Property<string>("InputTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("inputTypeName");

                    b.HasKey("InputTypeId");

                    b.ToTable("inputType", (string)null);
                });

            modelBuilder.Entity("slowfit.DBModels.LevelTraining", b =>
                {
                    b.Property<int>("LevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("levelId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LevelId"));

                    b.Property<string>("LevelString")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("levelString");

                    b.HasKey("LevelId");

                    b.ToTable("levelTraining", (string)null);
                });

            modelBuilder.Entity("slowfit.DBModels.LocationTraining", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("locationId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("LocationString")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("locationString");

                    b.HasKey("LocationId");

                    b.ToTable("locationTraining", (string)null);
                });

            modelBuilder.Entity("slowfit.DBModels.Meal", b =>
                {
                    b.Property<int>("MealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mealId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MealId"));

                    b.Property<int>("Calories")
                        .HasColumnType("int")
                        .HasColumnName("calories");

                    b.Property<int>("Carbohydrate")
                        .HasColumnType("int")
                        .HasColumnName("carbohydrate");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("categoryId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("description");

                    b.Property<int?>("Difficulty")
                        .HasColumnType("int")
                        .HasColumnName("difficulty");

                    b.Property<int>("Fats")
                        .HasColumnType("int")
                        .HasColumnName("fats");

                    b.Property<string>("ImageMeal")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("imageMeal");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int")
                        .HasColumnName("ingredientId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("PreparingTime")
                        .HasColumnType("int")
                        .HasColumnName("preparingTime");

                    b.Property<int>("Protein")
                        .HasColumnType("int")
                        .HasColumnName("protein");

                    b.Property<string>("Recipe")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("recipe");

                    b.HasKey("MealId");

                    b.HasIndex("CategoryId");

                    b.ToTable("meal", (string)null);
                });

            modelBuilder.Entity("slowfit.DBModels.MealIngredient", b =>
                {
                    b.Property<int>("MealId")
                        .HasColumnType("int")
                        .HasColumnName("mealId");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int")
                        .HasColumnName("ingredientId");

                    b.Property<double>("Quantity")
                        .HasColumnType("float")
                        .HasColumnName("quantity");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("unit");

                    b.HasKey("MealId", "IngredientId")
                        .HasName("PK__mealIngr__6F15A6E8793153BC");

                    b.HasIndex("IngredientId");

                    b.ToTable("mealIngredient", (string)null);
                });

            modelBuilder.Entity("slowfit.DBModels.Measure", b =>
                {
                    b.Property<int>("MeasureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("measureId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MeasureId"));

                    b.Property<int>("BodyId")
                        .HasColumnType("int")
                        .HasColumnName("bodyId");

                    b.Property<int>("Cm")
                        .HasColumnType("int")
                        .HasColumnName("cm");

                    b.Property<string>("CollectPeriod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("collectPeriod")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("MeasureId");

                    b.HasIndex("BodyId");

                    b.HasIndex("UserId");

                    b.ToTable("measure", (string)null);
                });

            modelBuilder.Entity("slowfit.DBModels.Nutrition", b =>
                {
                    b.Property<int>("NutritionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("nutritionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NutritionId"));

                    b.Property<string>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ExpirationDate")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("expirationDate");

                    b.Property<int>("MealId")
                        .HasColumnType("int")
                        .HasColumnName("mealId");

                    b.Property<int?>("TotDailyCalories")
                        .HasColumnType("int")
                        .HasColumnName("totDailyCalories");

                    b.Property<int>("TypeNutritionId")
                        .HasColumnType("int")
                        .HasColumnName("typeNutritionId");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("NutritionId");

                    b.HasIndex("TypeNutritionId");

                    b.ToTable("nutrition", (string)null);
                });

            modelBuilder.Entity("slowfit.DBModels.NutritionMeal", b =>
                {
                    b.Property<int>("MealId")
                        .HasColumnType("int")
                        .HasColumnName("mealId");

                    b.Property<int>("NutritionId")
                        .HasColumnType("int")
                        .HasColumnName("nutritionId");

                    b.HasIndex("MealId");

                    b.HasIndex("NutritionId");

                    b.ToTable("nutritionMeal", (string)null);
                });

            modelBuilder.Entity("slowfit.DBModels.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("orderId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("amount");

                    b.Property<string>("PaymentDate")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("paymentDate");

                    b.Property<int>("PaymentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("paymentTypeId");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("productId");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("OrderId");

                    b.HasIndex("PaymentTypeId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("order", (string)null);
                });

            modelBuilder.Entity("slowfit.DBModels.PaymentType", b =>
                {
                    b.Property<int>("PaymentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("paymentTypeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentTypeId"));

                    b.Property<string>("PaymentTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("paymentTypeName");

                    b.HasKey("PaymentTypeId");

                    b.ToTable("paymentType", (string)null);
                });

            modelBuilder.Entity("slowfit.DBModels.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("productId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("ExpirationDate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("expirationDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("price");

                    b.Property<int>("TypePlanId")
                        .HasColumnType("int")
                        .HasColumnName("typePlanId");

                    b.HasKey("ProductId");

                    b.HasIndex("TypePlanId");

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("slowfit.DBModels.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("questionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<string>("QuestionString")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("questionString");

                    b.HasKey("QuestionId");

                    b.ToTable("question", (string)null);
                });

            modelBuilder.Entity("slowfit.DBModels.Quiz", b =>
                {
                    b.Property<int>("QuizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("quizId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizId"));

                    b.Property<bool?>("Input")
                        .HasColumnType("bit")
                        .HasColumnName("input");

                    b.Property<int?>("InputTypeId")
                        .HasColumnType("int")
                        .HasColumnName("inputTypeId");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int")
                        .HasColumnName("questionId");

                    b.Property<bool>("SingleResponse")
                        .HasColumnType("bit")
                        .HasColumnName("singleResponse");

                    b.HasKey("QuizId");

                    b.HasIndex("InputTypeId");

                    b.HasIndex("QuestionId");

                    b.ToTable("quiz", (string)null);
                });

            modelBuilder.Entity("slowfit.DBModels.ResponseQuiz", b =>
                {
                    b.Property<int>("ResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("responseId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResponseId"));

                    b.Property<int>("AnswerId")
                        .HasColumnType("int")
                        .HasColumnName("answerId");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("ResponseId");

                    b.HasIndex("AnswerId");

                    b.HasIndex("UserId");

                    b.ToTable("responseQuiz", (string)null);
                });

            modelBuilder.Entity("slowfit.DBModels.RoleUser", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("roleId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("roleName");

                    b.HasKey("RoleId");

                    b.ToTable("roleUser", (string)null);
                });

            modelBuilder.Entity("slowfit.DBModels.Training", b =>
                {
                    b.Property<int>("TrainingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("trainingId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainingId"));

                    b.Property<string>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("creationDate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<string>("EndDate")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("endDate");

                    b.Property<int?>("LevelId")
                        .HasColumnType("int")
                        .HasColumnName("levelId");

                    b.Property<int>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("typeId");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("TrainingId");

                    b.HasIndex("LevelId");

                    b.HasIndex("TypeId");

                    b.ToTable("training", (string)null);
                });

            modelBuilder.Entity("slowfit.DBModels.TypeNutrition", b =>
                {
                    b.Property<int>("TypeNutritionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("typeNutritionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeNutritionId"));

                    b.Property<string>("TypeNutritionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("typeNutritionName");

                    b.HasKey("TypeNutritionId");

                    b.ToTable("typeNutrition", (string)null);
                });

            modelBuilder.Entity("slowfit.DBModels.TypePlan", b =>
                {
                    b.Property<int>("TypePlaneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("typePlaneId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypePlaneId"));

                    b.Property<string>("TypePlaneName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("typePlaneName");

                    b.HasKey("TypePlaneId");

                    b.ToTable("typePlan", (string)null);
                });

            modelBuilder.Entity("slowfit.DBModels.TypeTrainig", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("typeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("typeName");

                    b.HasKey("TypeId");

                    b.ToTable("typeTrainig", (string)null);
                });

            modelBuilder.Entity("slowfit.DBModels.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("address");

                    b.Property<string>("BirthDate")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("birthDate");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("country");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("firstName");

                    b.Property<string>("ImageProfile")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("imageProfile");

                    b.Property<int?>("NutritionId")
                        .HasColumnType("int")
                        .HasColumnName("nutritionId");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phone");

                    b.Property<string>("Province")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("province");

                    b.Property<int?>("PtId")
                        .HasColumnType("int")
                        .HasColumnName("ptId");

                    b.Property<int?>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("roleId");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("surname");

                    b.Property<int?>("TrainingId")
                        .HasColumnType("int")
                        .HasColumnName("trainingId");

                    b.Property<int?>("ZipCode")
                        .HasColumnType("int")
                        .HasColumnName("zipCode");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("slowfit.DBModels.Answer", b =>
                {
                    b.HasOne("slowfit.DBModels.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FK_answer_question");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("slowfit.DBModels.Appointment", b =>
                {
                    b.HasOne("slowfit.DBModels.User", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_appointment_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("slowfit.DBModels.Billing", b =>
                {
                    b.HasOne("slowfit.DBModels.Order", "Order")
                        .WithMany("Billings")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_billing_order");

                    b.HasOne("slowfit.DBModels.PaymentType", "PaymentType")
                        .WithMany("Billings")
                        .HasForeignKey("PaymentTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_billing_paymentType");

                    b.HasOne("slowfit.DBModels.User", "User")
                        .WithMany("Billings")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_billing_user");

                    b.Navigation("Order");

                    b.Navigation("PaymentType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("slowfit.DBModels.DetailExercise", b =>
                {
                    b.HasOne("slowfit.DBModels.Exercise", "Exercise")
                        .WithMany("DetailExercises")
                        .HasForeignKey("ExerciseId")
                        .IsRequired()
                        .HasConstraintName("FK_detailExercise_exercise");

                    b.HasOne("slowfit.DBModels.Training", "Training")
                        .WithMany("DetailExercises")
                        .HasForeignKey("TrainingId")
                        .IsRequired()
                        .HasConstraintName("FK_detailExercise_training");

                    b.Navigation("Exercise");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("slowfit.DBModels.Exercise", b =>
                {
                    b.HasOne("slowfit.DBModels.LocationTraining", "LocationTraining")
                        .WithMany("Exercises")
                        .HasForeignKey("LocationTrainingId")
                        .IsRequired()
                        .HasConstraintName("FK_exercise_locationTraining");

                    b.Navigation("LocationTraining");
                });

            modelBuilder.Entity("slowfit.DBModels.Meal", b =>
                {
                    b.HasOne("slowfit.DBModels.CategoryOfDay", "Category")
                        .WithMany("Meals")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_meal_categoryOfDay");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("slowfit.DBModels.MealIngredient", b =>
                {
                    b.HasOne("slowfit.DBModels.Ingredient", "Ingredient")
                        .WithMany("MealIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__mealIngre__ingre__220B0B18");

                    b.HasOne("slowfit.DBModels.Meal", "Meal")
                        .WithMany("MealIngredients")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__mealIngre__mealI__2116E6DF");

                    b.Navigation("Ingredient");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("slowfit.DBModels.Measure", b =>
                {
                    b.HasOne("slowfit.DBModels.BodyPart", "Body")
                        .WithMany("Measures")
                        .HasForeignKey("BodyId")
                        .IsRequired()
                        .HasConstraintName("FK_measure_bodyPart");

                    b.HasOne("slowfit.DBModels.User", "User")
                        .WithMany("Measures")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_measure_user");

                    b.Navigation("Body");

                    b.Navigation("User");
                });

            modelBuilder.Entity("slowfit.DBModels.Nutrition", b =>
                {
                    b.HasOne("slowfit.DBModels.TypeNutrition", "TypeNutrition")
                        .WithMany("Nutritions")
                        .HasForeignKey("TypeNutritionId")
                        .IsRequired()
                        .HasConstraintName("FK_nutrition_typeNutrition");

                    b.Navigation("TypeNutrition");
                });

            modelBuilder.Entity("slowfit.DBModels.NutritionMeal", b =>
                {
                    b.HasOne("slowfit.DBModels.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("MealId")
                        .IsRequired()
                        .HasConstraintName("FK_nutritionMeal_meal");

                    b.HasOne("slowfit.DBModels.Nutrition", "Nutrition")
                        .WithMany()
                        .HasForeignKey("NutritionId")
                        .IsRequired()
                        .HasConstraintName("FK_nutritionMeal_nutrition");

                    b.Navigation("Meal");

                    b.Navigation("Nutrition");
                });

            modelBuilder.Entity("slowfit.DBModels.Order", b =>
                {
                    b.HasOne("slowfit.DBModels.PaymentType", "PaymentType")
                        .WithMany("Orders")
                        .HasForeignKey("PaymentTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_order_paymentType");

                    b.HasOne("slowfit.DBModels.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_order_product");

                    b.HasOne("slowfit.DBModels.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_order_user");

                    b.Navigation("PaymentType");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("slowfit.DBModels.Product", b =>
                {
                    b.HasOne("slowfit.DBModels.TypePlan", "TypePlan")
                        .WithMany("Products")
                        .HasForeignKey("TypePlanId")
                        .IsRequired()
                        .HasConstraintName("FK_product_typePlan");

                    b.Navigation("TypePlan");
                });

            modelBuilder.Entity("slowfit.DBModels.Quiz", b =>
                {
                    b.HasOne("slowfit.DBModels.InputType", "InputType")
                        .WithMany("Quizzes")
                        .HasForeignKey("InputTypeId")
                        .HasConstraintName("FK_quiz_inputType");

                    b.HasOne("slowfit.DBModels.Question", "Question")
                        .WithMany("Quizzes")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FK_quiz_question");

                    b.Navigation("InputType");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("slowfit.DBModels.ResponseQuiz", b =>
                {
                    b.HasOne("slowfit.DBModels.Answer", "Answer")
                        .WithMany("ResponseQuizzes")
                        .HasForeignKey("AnswerId")
                        .IsRequired()
                        .HasConstraintName("FK_responseQuiz_answer");

                    b.HasOne("slowfit.DBModels.User", "User")
                        .WithMany("ResponseQuizzes")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_responseQuiz_user");

                    b.Navigation("Answer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("slowfit.DBModels.Training", b =>
                {
                    b.HasOne("slowfit.DBModels.LevelTraining", "Level")
                        .WithMany("Training")
                        .HasForeignKey("LevelId")
                        .HasConstraintName("FK_training_levelTraining");

                    b.HasOne("slowfit.DBModels.TypeTrainig", "Type")
                        .WithMany("Training")
                        .HasForeignKey("TypeId")
                        .IsRequired()
                        .HasConstraintName("FK_training_typeTrainig");

                    b.Navigation("Level");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("slowfit.DBModels.User", b =>
                {
                    b.HasOne("slowfit.DBModels.RoleUser", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_user_roleUser");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("slowfit.DBModels.Answer", b =>
                {
                    b.Navigation("ResponseQuizzes");
                });

            modelBuilder.Entity("slowfit.DBModels.BodyPart", b =>
                {
                    b.Navigation("Measures");
                });

            modelBuilder.Entity("slowfit.DBModels.CategoryOfDay", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("slowfit.DBModels.Exercise", b =>
                {
                    b.Navigation("DetailExercises");
                });

            modelBuilder.Entity("slowfit.DBModels.Ingredient", b =>
                {
                    b.Navigation("MealIngredients");
                });

            modelBuilder.Entity("slowfit.DBModels.InputType", b =>
                {
                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("slowfit.DBModels.LevelTraining", b =>
                {
                    b.Navigation("Training");
                });

            modelBuilder.Entity("slowfit.DBModels.LocationTraining", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("slowfit.DBModels.Meal", b =>
                {
                    b.Navigation("MealIngredients");
                });

            modelBuilder.Entity("slowfit.DBModels.Order", b =>
                {
                    b.Navigation("Billings");
                });

            modelBuilder.Entity("slowfit.DBModels.PaymentType", b =>
                {
                    b.Navigation("Billings");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("slowfit.DBModels.Product", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("slowfit.DBModels.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("slowfit.DBModels.RoleUser", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("slowfit.DBModels.Training", b =>
                {
                    b.Navigation("DetailExercises");
                });

            modelBuilder.Entity("slowfit.DBModels.TypeNutrition", b =>
                {
                    b.Navigation("Nutritions");
                });

            modelBuilder.Entity("slowfit.DBModels.TypePlan", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("slowfit.DBModels.TypeTrainig", b =>
                {
                    b.Navigation("Training");
                });

            modelBuilder.Entity("slowfit.DBModels.User", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Billings");

                    b.Navigation("Measures");

                    b.Navigation("Orders");

                    b.Navigation("ResponseQuizzes");
                });
#pragma warning restore 612, 618
        }
    }
}
